import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(public)/components/Nav";
import Footer from "./(public)/components/Footer";
import { AppProvider } from "./context/AppContext";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >

      <body className="bg-[#F9f9f9] dark:bg-[#07111F] dark:text-[#F8FAFC] min-h-full flex flex-col scroll-smooth">
        <AppProvider>
          <Nav />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
