import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(public)/landing-sections/Nav";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const viewport:  Viewport = {
  width: "device-width",
  initialScale: 1,
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col scroll-smooth">
        <Nav />
        {children}
      </body>
    </html>
  );
}
